name: CI
on:
  workflow_dispatch:
    inputs:
      domain:
        default: 'stridespace.com'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: testspace-com/setup-testspace@v1
        with:
          domain: ${{ github.repository_owner }}.${{ inputs.domain}}
      - name: Push result to Testspace server
        run: |
          testspace "[automated results]results.xml"
        if: always()